package io.github.ozozorz.aipartner.contract;

/**
 * 把验证与运行时故障归一化，便于一致性回复和故障诊断。
 */
public enum FailureCode {
    NONE,
    PARTNER_DIED,
    OWNER_OFFLINE,
    DIFFERENT_DIMENSION,
    TARGET_NOT_FOUND,
    TARGET_DISAPPEARED,
    PATH_UNREACHABLE,
    MISSING_TOOL,
    MISSING_ITEM,
    INVENTORY_FULL,
    CONTAINER_FULL,
    PERMISSION_DENIED,
    INVALID_PARAMETER,
    CONTRACT_VIOLATION,
    UNSUPPORTED_JOB,
    TIMEOUT,
    CANCELLED_BY_PLAYER,
    INTERNAL_ERROR
}
